services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    ports:
      - "5001:${PORT:-80}"
    # env_file:
    #   - .env
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_URL=${DB_URL:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-dev}
      - SECRET_KEY=${SECRET_KEY:-my_precious}
      - PORT=${PORT:-80}
      - STATIC_S3_BUCKET=${STATIC_S3_BUCKET:-soa-dev-profile-images}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_TO_STDOUT=${LOG_TO_STDOUT:-false}
    depends_on:
      - db
    links:
      - db

  db:
    container_name: db
    build:
      context: ./backend/project/database
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
